### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by danxshap** [disqus/django-mailviews#14]
Is there a best-practice way to pip install this project from source/Github?

For every other python project I've encountered I've simply had to use `pip install git+[git url]` or `pip install -e [git_url]` but for this project it doesn't work because the Bootstrap files need to be compiled and copied. Looks like the package on PyPi is precompiled i.e. different than the contents of this repo, which I guess is the fundamental difference I'm seeing between this and other projects (at least that I'm aware of).

Just trying to avoid having to resort to a comment in my requirements.txt that says "You need to run 'make' after you install this"

**Comment by tkaemming** [comment]
There's not really a great way to do this, since as you mentioned the static assets still need to be built.

The parts of the `Makefile` that handle building assets *could* be ported to Python (that way you could control it from your application after the package was installed from source, without prebuilt assets) but I think that is out of the scope of this project for now.

In general, it's probably a better idea to use the PyPI releases (sorry that they have lagged in between versions), or build and host your own source distribution if you want to deploy the latest revision.
